### ISSUE TITLE
Should web hooks run on a separate domain?

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib.org#10]
When initially spinning up the droplet, I put it on `do.matplotlib.org` so we could test load a bit. I also configured all web hooks using that domain.

Now that `matplotlib.org` is pointing to the droplets, I modified Caddy to serve the _same_ thing from both domains so that nothing breaks. However, that's a bit redundant, and we don't really need CF to be CDN'ing things twice (though I don't expect anyone to be accessing the duplicated subdomain.)

We can update the web hooks to point to `matplotlib.org` easily, but I wonder if we should leave them on a separate domain still? They'd still be served by the same server, but that would silo off the paths just in case we needed them (though that's unlikely).

**Comment by tacaswell** [comment]
I would leave these on a separate domain for the webhooks to keep the "reads" and the "writes" separate.
