### ISSUE TITLE
Do we need to be able to run Caddy from a checkout directly?

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib.org#11]
Initially, I wrote the `Caddyfile` to be able to be run locally. With the Ansible config added, we have a couple redundancies defining, e.g., the list of subrepos to clone and serve. We can remove that redundancy by making the Caddyfile a template, but then it can't be run directly.

I recently came across [ansible-bender](https://ansible-community.github.io/ansible-bender/), so I think we could maybe point local testing there (it takes an Ansible config and applies it to a container instead of your configured hosts.)

**Comment by tacaswell** [comment]
I would prefer to switch to the template and then sort out how to run against a local target.
